### ISSUE TITLE
`run` wrapper doesn't detect newly added containers

### ISSUE THREAD

**Issue by pvanheus** [Banshee1221/singularity-wrapper#2]
I built a GATK4 wrapper and put it in `/tools/containers/gatk/gatk-4.1.2.0--1.simg`. It neither showed up in the list shown with `--tools` nor was it executable by specifying `--version=4.1.2.0--1.simg`.

**Comment by Banshee1221** [comment]
The wrapped uses a json file generated by daemon.py. This needs to be triggered to run on change in directory or on a regular basis via cron
